image: node:18

cache:
  key: "$CI_COMMIT_REF_NAME"
  paths:
    - node_modules
    - functions/node_modules
  policy: push

stages:
  - prepare
  - deploy

npm-install:
  stage: prepare
  script:
    - yarn

deploy-production:
  stage: deploy
  script:
    - yarn install
    - yarn global add firebase-tools@12.4.5
    - yarn add firebase-functions
    - echo $GCLOUD_SERVICE_KEY | base64 -d > $GOOGLE_APPLICATION_CREDENTIALS
    - firebase projects:list --debug
    - firebase use 1334648084 --debug
    - yarn deployci
  environment:
    name: production
    url: https://janaicoffee.tokyo/
  only:
    - master
  when: manual

deploy-staging:
  stage: deploy
  script:
    - yarn install
    - yarn global add firebase-tools@12.4.5
    - yarn add firebase-functions
    - echo $GCLOUD_SERVICE_KEY | base64 -d > $GOOGLE_APPLICATION_CREDENTIALS
    - firebase projects:list --debug
    - firebase use 1334648084 --debug
    - yarn deploycistg
  environment:
    name: staging
    url: https://janaicoffee-stg.firebaseapp.com/
  only:
    - develop
  when: manual